name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  native-os-build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: "1.15"
      - name: Build native
        run: go build -v ./...
        shell: bash
      - name: Run unit tests
        run: go test -v -race ./...
        shell: bash
      - name: Cross-build for 386
        if: matrix.os != 'macOS-latest'
        run: GOARCH=386 go build -v ./...
        shell: bash
      - name: Cross-build for arm
        if: matrix.os != 'macOS-latest'
        run: GOARCH=arm go build -v ./...
        shell: bash
